### ISSUE TITLE
Add GLOBAL -> SLIM transpiler

### ISSUE THREAD

**Issue by m-mujica** [stealjs/transpile#81]
If you use the current version on the slim branch, the global will be transpiled to amd then to slim; you'd get something like this: 

![screen shot 2017-05-25 at 11 18 15](https://cloud.githubusercontent.com/assets/724877/26464611/998af486-4145-11e7-9c18-a173ef6549d2.png)

which won't work.

**Comment by matthewp** [comment]
The only reason the current global format is that gross is to support this style of global:

```js
var MooTools = {};
```

Yep, it's for mootools. In transpile@2 we'll drop support for that. *However*, since slim is a new format we don't need to support it at all there.

So the way to do a global would be to inline the code directly in that function; that's it.

**Comment by m-mujica** [comment]
https://github.com/stealjs/transpile/issues/88#issuecomment-310719095
